### ISSUE TITLE
Make use of the `type` property to detect bots

### ISSUE THREAD

**Issue by gomorizsolt** [c-hive/fresh-bot#17]
Comment: https://github.com/c-hive/fresh-bot/pull/14#issuecomment-657460137. Let's use the `type` property instead of [regexes](https://github.com/c-hive/fresh-bot/blob/4759637773779df047598089563ebc2b1215b0ef/index.js#L29-L38) to detect comments from bots.

**Comment by thisismydesign** [comment]
I would still use both, the type field is just to make sure there are no false positives.

**Comment by thisismydesign** [comment]
Addressed in https://github.com/c-hive/fresh-bot/commit/2861026fb08b778e7515602f55d08b294fe3b401
We now check the type field instead of the name field
