### ISSUE TITLE
Use `actions-tagger` to automatically update major version tags

### ISSUE THREAD

**Issue by gomorizsolt** [c-hive/fresh-bot#19]
I'd automate the major version binding, mostly just for the sake of convenience.

Resources:
- article: https://michaelheap.com/semantic-versioning-for-github-actions/
- action: https://github.com/marketplace/actions/actions-tagger

**Comment by thisismydesign** [comment]
Closed in https://github.com/c-hive/fresh-bot/commit/dc43da4a8e4fe149278d0231c88703a5e2cbcdd3. Thanks for the proposal!
